### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'do_exit'

### ISSUE THREAD

**Issue by soer7022** [TNThieding/pylint-fail-under#4]
When I try to run the package I get the following error:

```
$pylint-fail-under --fail-under 9.0 lama 
WARNING: no fail_under argument provided, defaulting to 10.0
Traceback (most recent call last):
  File "/usr/local/bin/pylint-fail-under", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pylint_fail_under/__main__.py", line 38, in main
    results = Run(args=cmd_line_args, do_exit=False)
TypeError: __init__() got an unexpected keyword argument 'do_exit'
```
Python version:
```
python --version
Python 2.7.16
```
Package version:
```
$pip show pylint-fail-under
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: pylint-fail-under
Version: 0.3.0
Summary: Pylint wrapper that verifies code reaches a minimum quality score.
Home-page: https://github.com/TNThieding/pylint-fail-under
Author: Tyler N. Thieding
Author-email: python@thieding.com
License: MIT License
Location: /usr/local/lib/python2.7/site-packages
Requires: pylint
Required-by: LAMA-API
```
Pylint version:
```
$pip show pylint
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: pylint
Version: 1.9.5
Summary: python code static checker
Home-page: https://github.com/PyCQA/pylint
Author: Python Code Quality Authority
Author-email: code-quality@python.org
License: GPL
Location: /usr/local/lib/python2.7/site-packages
Requires: astroid, six, isort, singledispatch, mccabe, configparser, backports.functools-lru-cache
Required-by: pylint-fail-under, LAMA-API
```

**Comment by soer7022** [comment]
Bump

**Comment by TNThieding** [comment]
This package does not support Python 2 as it has long been deprecated. Could you please verify that this anomaly occurs in Python 3?

**Comment by soer7022** [comment]
Sorry, it works in python 3
