### ISSUE TITLE
pylint-fail-under fails with pylint 2.5.1

### ISSUE THREAD

**Issue by kagarlickij** [TNThieding/pylint-fail-under#8]
When I use `pylint-fail-under` with pylint 2.5.0 it works correctly:
```
root@cecc60f98dd3:/opt# pylint --version
pylint 2.5.0
astroid 2.4.1
Python 3.7.7 (default, Apr 23 2020, 14:43:26) 
[GCC 8.3.0]
root@cecc60f98dd3:/opt# pylint-fail-under --fail_under 8.00 ./**/*.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

..but whits pylint 2.5.1 (the latest one at the moment) it fails:
```
root@cecc60f98dd3:/opt# pylint --version
pylint 2.5.1
astroid 2.4.1
Python 3.7.7 (default, Apr 23 2020, 14:43:26) 
[GCC 8.3.0]
root@cecc60f98dd3:/opt# pylint-fail-under --fail_under 8.00 ./**/*.py
Traceback (most recent call last):
  File "/usr/local/bin/pylint-fail-under", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pylint_fail_under/__main__.py", line 38, in main
    results = Run(args=cmd_line_args, do_exit=False)
TypeError: __init__() got an unexpected keyword argument 'do_exit'
```

**Comment by TNThieding** [comment]
Thank you for bringing this to my attention. For reference, Pylint 2.5.0 added a ``--fail-under`` argument that natively does the same thing as this package. For that reason, I don't plan on much  more active development with this package for newer versions of Pylint.

See the Pylint release notes for more: http://pylint.pycqa.org/en/latest/whatsnew/2.5.html#other-changes
